<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>notReferenced</name>
  <uuid>735f9130-eef4-4fa0-80bd-67b8a116ccc9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is not a known city and Name is not a known country 
then
    print Name + " is not a referenced capital or country, check its spelling";
	set decision to null ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
