<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>checkFrom</name>
  <uuid>3afdf1e9-ab82-477b-984a-b8d1bb506366</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Origin location' is undefined 
then
    print "The origin is not a known capital or country, please check its spelling";
	set decision to -1 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
