<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>computeDistance</name>
  <uuid>1ce09217-7ed7-4cd3-8bbb-bae454b7aab5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the distance computed from
      Origin being Origin , 
      Destination being Destination ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
