<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>checkDistance</name>
  <uuid>9f494dd5-cbac-454a-9dc7-c2a1f49ecfa2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Compute distance' equals -1 
then
    print "The distance between " + Origin + " and " + Destination + " cannot be computed";
	set decision to -1 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
