<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>checkDestination</name>
  <uuid>d15824a2-ff4a-4d2d-a538-838280bcab6f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
 'Destination location' is undefined 
 then 
   set decision to -1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
