<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>checkOrigin</name>
  <uuid>3211dc08-6077-481e-90b1-d300ffd6f881</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
 'Origin location' is undefined 
then
   set decision to -1 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
