<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>computeDistance</name>
  <uuid>8913b4e8-49a6-43e1-a3ab-fd914cc652eb</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the distance between 'Origin location' and 'Destination location' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
